#!/bin/sh

if [ "$BLOCK_BUTTON" = "1" ]; then
	setsid -f "$TERMINAL" -e calcurse
fi

clock=$(date '+%I')

case "$clock" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

icon=""

bg="#f38ba8"
fg="#313244"

#dbg="$(xgetres color13)"
#dbg=${dbg:="#001429"}
#bg="$(xgetres color13)"
#bg=${bg:="#001f3d"}
printf "^c$fg^^b$bg^ %s ^d^^c$bg^ %s^d^" "$icon" "$(date '+%a, %d %b %H:%M')"

