#!/bin/bash

# if spotify is started
if [ "$(pidof spotify)" ]; then
    # status can be: Playing, Paused or Stopped
    status=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'| grep -E -A 1 "string"|cut -b 26-|cut -d '"' -f 1| grep -E -v ^$`
    metadata=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`
    artist=`echo "$metadata"|grep -E -A 2 "artist"|grep -E -v "artist"|grep -E -v "array"|cut -b 27-|cut -d '"' -f 1|grep -E -v ^$`
    # artist would be empty on ads
    if [ "$status" = "Playing" ] && [ ! -z "$artist" ]; then
    	title=`echo "$metadata"|grep -E -A 1 "title"|grep -E -v "title"|cut -b 44-|cut -d '"' -f 1|grep -E -v ^$`
	printf "^c#191414^^b#1db954^  ^c#191414^^b#1ed960^ %s ^d^" "$(sb-strcut 40 "$artist - $title")"
    fi
fi
